services:
  - type: web
    name: boxful-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:prod
    healthCheckPath: /api/docs
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: PORT
        value: 3001
